name: VTune hotspots analysis (docker)

on:
  workflow_dispatch:

jobs:
  vtune-analysis:
    runs-on: ubuntu-latest
    env: 
      PRCOMMITSHA : ${{ github.event.pull_request.head.sha }}

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref:
            CI/automated-profiling
      
      # Step 2: Build the Docker image
      - name: Build Docker Image
        run: |
           docker build -t ci-vtune-aegis \
                        --build-arg build_git_sha="${PRCOMMITSHA:-$GITHUB_SHA}" \
                        --build-arg build_git_repo="${PRREPOSITORY:-$GITHUB_REPOSITORY}" \
                        docker/vtune-ci/
      
      - name: Start Docker container
        run: |
          docker run --name profiling-container ci-vtune-aegis sh 
          
      - name: Copy artifact from container
        run: |
          docker cp profiling-container:/opt/artifacts/hotspots_summary.html ./hotspots_summary.html
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vtune-hotspots-results
          path: ./hotspots_summary
